PACKAGES=(
  yo
  yeoman-generator
  generator-generator
  yarn
  @angular/cli
  generator-ss-validate-commit-msg
  generator-ss-standard-version
  generator-ss-ansible-playbook
  vue-cli
)

LINKS=(
  flask
  jenkins
  elasticsearch-kibana
  consul-servers
)

upgrade-nodebrew() {
  if [ $# -ne 1 ]; then
    echo "the number of argument should be 1" 1>&2
    exit 1
  fi
  NODE_VERSION=$1

  nodebrew install-binary $NODE_VERSION
  nodebrew use $NODE_VERSION

  npm i -g $PACKAGES

  for LINK in "${LINKS[@]}"; do
    ghq get suzuki-shunsuke/generator-ss-$LINK
    cd `ghq root`/github.com/suzuki-shunsuke/generator-ss-$LINK
    if [ -d node_modules ]; then
      rm -R node_modules
    fi
    npm link
  done
}
