# docker
# dckrm
# dckrmi

alias dps='docker-compose ps'
alias dup='docker-compose up -d'
alias dstp='docker-compose stop'
alias drst='docker-compose restart'
alias dexc='docker-compose exec'
alias drm='docker-compose rm'
alias dbuild='docker build -t'
alias dimg='docker images'
alias dpush='docker push'
